//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 08:24:41 AM CDT 
//


package com.techolution.bi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BarcodeTxDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BarcodeTxDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ManualEntry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsActual" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcceptorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcceptorOrdinal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BarcodeTxDataType", propOrder = {
    "barcode",
    "manualEntry",
    "isActual",
    "acceptorId",
    "acceptorOrdinal"
})
public class BarcodeTxDataType {

    @XmlElement(name = "Barcode", required = true)
    protected String barcode;
    @XmlElement(name = "ManualEntry", required = true)
    protected String manualEntry;
    @XmlElement(name = "IsActual", required = true)
    protected String isActual;
    @XmlElement(name = "AcceptorId", required = true)
    protected String acceptorId;
    @XmlElement(name = "AcceptorOrdinal", required = true)
    protected String acceptorOrdinal;

    /**
     * Gets the value of the barcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the manualEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualEntry() {
        return manualEntry;
    }

    /**
     * Sets the value of the manualEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualEntry(String value) {
        this.manualEntry = value;
    }

    /**
     * Gets the value of the isActual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActual() {
        return isActual;
    }

    /**
     * Sets the value of the isActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActual(String value) {
        this.isActual = value;
    }

    /**
     * Gets the value of the acceptorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptorId() {
        return acceptorId;
    }

    /**
     * Sets the value of the acceptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptorId(String value) {
        this.acceptorId = value;
    }

    /**
     * Gets the value of the acceptorOrdinal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptorOrdinal() {
        return acceptorOrdinal;
    }

    /**
     * Sets the value of the acceptorOrdinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptorOrdinal(String value) {
        this.acceptorOrdinal = value;
    }

}
