//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 08:24:41 AM CDT 
//


package com.techolution.bi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.techolution.bi.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RevolutionTransactions_QNAME = new QName("", "RevolutionTransactions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.techolution.bi.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RevolutionTransactionsType }
     * 
     */
    public RevolutionTransactionsType createRevolutionTransactionsType() {
        return new RevolutionTransactionsType();
    }

    /**
     * Create an instance of {@link TotalValueType }
     * 
     */
    public TotalValueType createTotalValueType() {
        return new TotalValueType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link ImageTxDataType }
     * 
     */
    public ImageTxDataType createImageTxDataType() {
        return new ImageTxDataType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link BarcodeTxDataType }
     * 
     */
    public BarcodeTxDataType createBarcodeTxDataType() {
        return new BarcodeTxDataType();
    }

    /**
     * Create an instance of {@link VaultFundType }
     * 
     */
    public VaultFundType createVaultFundType() {
        return new VaultFundType();
    }

    /**
     * Create an instance of {@link CreateTimeType }
     * 
     */
    public CreateTimeType createCreateTimeType() {
        return new CreateTimeType();
    }

    /**
     * Create an instance of {@link ExtraDetailsType }
     * 
     */
    public ExtraDetailsType createExtraDetailsType() {
        return new ExtraDetailsType();
    }

    /**
     * Create an instance of {@link RegisterType }
     * 
     */
    public RegisterType createRegisterType() {
        return new RegisterType();
    }

    /**
     * Create an instance of {@link CashFundTransferTxDataType }
     * 
     */
    public CashFundTransferTxDataType createCashFundTransferTxDataType() {
        return new CashFundTransferTxDataType();
    }

    /**
     * Create an instance of {@link MiscDataType }
     * 
     */
    public MiscDataType createMiscDataType() {
        return new MiscDataType();
    }

    /**
     * Create an instance of {@link DestinationUserType }
     * 
     */
    public DestinationUserType createDestinationUserType() {
        return new DestinationUserType();
    }

    /**
     * Create an instance of {@link CustomDataType }
     * 
     */
    public CustomDataType createCustomDataType() {
        return new CustomDataType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link MoneyTxDataType }
     * 
     */
    public MoneyTxDataType createMoneyTxDataType() {
        return new MoneyTxDataType();
    }

    /**
     * Create an instance of {@link MachineType }
     * 
     */
    public MachineType createMachineType() {
        return new MachineType();
    }

    /**
     * Create an instance of {@link DepartmentType }
     * 
     */
    public DepartmentType createDepartmentType() {
        return new DepartmentType();
    }

    /**
     * Create an instance of {@link RetrievalDateType }
     * 
     */
    public RetrievalDateType createRetrievalDateType() {
        return new RetrievalDateType();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link DbChangeType }
     * 
     */
    public DbChangeType createDbChangeType() {
        return new DbChangeType();
    }

    /**
     * Create an instance of {@link MoneyType }
     * 
     */
    public MoneyType createMoneyType() {
        return new MoneyType();
    }

    /**
     * Create an instance of {@link ErrorTxDataType }
     * 
     */
    public ErrorTxDataType createErrorTxDataType() {
        return new ErrorTxDataType();
    }

    /**
     * Create an instance of {@link WadType }
     * 
     */
    public WadType createWadType() {
        return new WadType();
    }

    /**
     * Create an instance of {@link OriginatingUserType }
     * 
     */
    public OriginatingUserType createOriginatingUserType() {
        return new OriginatingUserType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link NetValueType }
     * 
     */
    public NetValueType createNetValueType() {
        return new NetValueType();
    }

    /**
     * Create an instance of {@link AccountingPeriodType }
     * 
     */
    public AccountingPeriodType createAccountingPeriodType() {
        return new AccountingPeriodType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevolutionTransactionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RevolutionTransactions")
    public JAXBElement<RevolutionTransactionsType> createRevolutionTransactions(RevolutionTransactionsType value) {
        return new JAXBElement<RevolutionTransactionsType>(_RevolutionTransactions_QNAME, RevolutionTransactionsType.class, null, value);
    }

}
