//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 08:24:41 AM CDT 
//


package com.techolution.bi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Modified" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{}TypeType"/>
 *         &lt;element name="CreateTime" type="{}CreateTimeType"/>
 *         &lt;element name="AccountingPeriod" type="{}AccountingPeriodType"/>
 *         &lt;element name="Machine" type="{}MachineType"/>
 *         &lt;element name="OriginatingUser" type="{}OriginatingUserType"/>
 *         &lt;element name="DestinationUser" type="{}DestinationUserType"/>
 *         &lt;element name="Department" type="{}DepartmentType"/>
 *         &lt;element name="Register" type="{}RegisterType"/>
 *         &lt;element name="TillBarcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParentTxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChildTxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExtraDetails" type="{}ExtraDetailsType"/>
 *         &lt;element name="Device" type="{}DeviceType"/>
 *         &lt;element name="MiscData" type="{}MiscDataType"/>
 *         &lt;element name="ErrorTxData" type="{}ErrorTxDataType"/>
 *         &lt;element name="BarcodeTxData" type="{}BarcodeTxDataType"/>
 *         &lt;element name="MoneyTxData" type="{}MoneyTxDataType"/>
 *         &lt;element name="CashFundTransferTxData" type="{}CashFundTransferTxDataType"/>
 *         &lt;element name="ImageTxData" type="{}ImageTxDataType"/>
 *         &lt;element name="BagNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RetrievalDate" type="{}RetrievalDateType"/>
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExtendedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VaultFund" type="{}VaultFundType"/>
 *         &lt;element name="DbChange" type="{}DbChangeType"/>
 *         &lt;element name="IsPreExchange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DoorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SoftwareVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BagCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CashBagCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CheckBagCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MediaDetected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetValue" type="{}NetValueType"/>
 *         &lt;element name="CustomData" type="{}CustomDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionType", propOrder = {
    "modified",
    "id",
    "type",
    "createTime",
    "accountingPeriod",
    "machine",
    "originatingUser",
    "destinationUser",
    "department",
    "register",
    "tillBarcode",
    "parentTxId",
    "childTxId",
    "extraDetails",
    "device",
    "miscData",
    "errorTxData",
    "barcodeTxData",
    "moneyTxData",
    "cashFundTransferTxData",
    "imageTxData",
    "bagNumber",
    "deviceType",
    "retrievalDate",
    "reason",
    "extendedType",
    "vaultFund",
    "dbChange",
    "isPreExchange",
    "deviceErrorCode",
    "doorName",
    "softwareVersion",
    "bagCount",
    "cashBagCount",
    "checkBagCount",
    "mediaDetected",
    "netValue",
    "customData"
})
public class TransactionType {

    @XmlElement(name = "Modified", required = true)
    protected String modified;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Type", required = true)
    protected TypeType type;
    @XmlElement(name = "CreateTime", required = true)
    protected CreateTimeType createTime;
    @XmlElement(name = "AccountingPeriod", required = true)
    protected AccountingPeriodType accountingPeriod;
    @XmlElement(name = "Machine", required = true)
    protected MachineType machine;
    @XmlElement(name = "OriginatingUser", required = true)
    protected OriginatingUserType originatingUser;
    @XmlElement(name = "DestinationUser", required = true)
    protected DestinationUserType destinationUser;
    @XmlElement(name = "Department", required = true)
    protected DepartmentType department;
    @XmlElement(name = "Register", required = true)
    protected RegisterType register;
    @XmlElement(name = "TillBarcode", required = true)
    protected String tillBarcode;
    @XmlElement(name = "ParentTxId", required = true)
    protected String parentTxId;
    @XmlElement(name = "ChildTxId", required = true)
    protected String childTxId;
    @XmlElement(name = "ExtraDetails", required = true)
    protected ExtraDetailsType extraDetails;
    @XmlElement(name = "Device", required = true)
    protected DeviceType device;
    @XmlElement(name = "MiscData", required = true)
    protected MiscDataType miscData;
    @XmlElement(name = "ErrorTxData", required = true)
    protected ErrorTxDataType errorTxData;
    @XmlElement(name = "BarcodeTxData", required = true)
    protected BarcodeTxDataType barcodeTxData;
    @XmlElement(name = "MoneyTxData", required = true)
    protected MoneyTxDataType moneyTxData;
    @XmlElement(name = "CashFundTransferTxData", required = true)
    protected CashFundTransferTxDataType cashFundTransferTxData;
    @XmlElement(name = "ImageTxData", required = true)
    protected ImageTxDataType imageTxData;
    @XmlElement(name = "BagNumber", required = true)
    protected String bagNumber;
    @XmlElement(name = "DeviceType", required = true)
    protected String deviceType;
    @XmlElement(name = "RetrievalDate", required = true)
    protected RetrievalDateType retrievalDate;
    @XmlElement(name = "Reason", required = true)
    protected String reason;
    @XmlElement(name = "ExtendedType", required = true)
    protected String extendedType;
    @XmlElement(name = "VaultFund", required = true)
    protected VaultFundType vaultFund;
    @XmlElement(name = "DbChange", required = true)
    protected DbChangeType dbChange;
    @XmlElement(name = "IsPreExchange", required = true)
    protected String isPreExchange;
    @XmlElement(name = "DeviceErrorCode", required = true)
    protected String deviceErrorCode;
    @XmlElement(name = "DoorName", required = true)
    protected String doorName;
    @XmlElement(name = "SoftwareVersion", required = true)
    protected String softwareVersion;
    @XmlElement(name = "BagCount", required = true)
    protected String bagCount;
    @XmlElement(name = "CashBagCount", required = true)
    protected String cashBagCount;
    @XmlElement(name = "CheckBagCount", required = true)
    protected String checkBagCount;
    @XmlElement(name = "MediaDetected", required = true)
    protected String mediaDetected;
    @XmlElement(name = "NetValue", required = true)
    protected NetValueType netValue;
    @XmlElement(name = "CustomData", required = true)
    protected CustomDataType customData;

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModified(String value) {
        this.modified = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeType }
     *     
     */
    public TypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeType }
     *     
     */
    public void setType(TypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link CreateTimeType }
     *     
     */
    public CreateTimeType getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateTimeType }
     *     
     */
    public void setCreateTime(CreateTimeType value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the accountingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingPeriodType }
     *     
     */
    public AccountingPeriodType getAccountingPeriod() {
        return accountingPeriod;
    }

    /**
     * Sets the value of the accountingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingPeriodType }
     *     
     */
    public void setAccountingPeriod(AccountingPeriodType value) {
        this.accountingPeriod = value;
    }

    /**
     * Gets the value of the machine property.
     * 
     * @return
     *     possible object is
     *     {@link MachineType }
     *     
     */
    public MachineType getMachine() {
        return machine;
    }

    /**
     * Sets the value of the machine property.
     * 
     * @param value
     *     allowed object is
     *     {@link MachineType }
     *     
     */
    public void setMachine(MachineType value) {
        this.machine = value;
    }

    /**
     * Gets the value of the originatingUser property.
     * 
     * @return
     *     possible object is
     *     {@link OriginatingUserType }
     *     
     */
    public OriginatingUserType getOriginatingUser() {
        return originatingUser;
    }

    /**
     * Sets the value of the originatingUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginatingUserType }
     *     
     */
    public void setOriginatingUser(OriginatingUserType value) {
        this.originatingUser = value;
    }

    /**
     * Gets the value of the destinationUser property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationUserType }
     *     
     */
    public DestinationUserType getDestinationUser() {
        return destinationUser;
    }

    /**
     * Sets the value of the destinationUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationUserType }
     *     
     */
    public void setDestinationUser(DestinationUserType value) {
        this.destinationUser = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link DepartmentType }
     *     
     */
    public DepartmentType getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartmentType }
     *     
     */
    public void setDepartment(DepartmentType value) {
        this.department = value;
    }

    /**
     * Gets the value of the register property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterType }
     *     
     */
    public RegisterType getRegister() {
        return register;
    }

    /**
     * Sets the value of the register property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterType }
     *     
     */
    public void setRegister(RegisterType value) {
        this.register = value;
    }

    /**
     * Gets the value of the tillBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTillBarcode() {
        return tillBarcode;
    }

    /**
     * Sets the value of the tillBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTillBarcode(String value) {
        this.tillBarcode = value;
    }

    /**
     * Gets the value of the parentTxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentTxId() {
        return parentTxId;
    }

    /**
     * Sets the value of the parentTxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentTxId(String value) {
        this.parentTxId = value;
    }

    /**
     * Gets the value of the childTxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildTxId() {
        return childTxId;
    }

    /**
     * Sets the value of the childTxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildTxId(String value) {
        this.childTxId = value;
    }

    /**
     * Gets the value of the extraDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDetailsType }
     *     
     */
    public ExtraDetailsType getExtraDetails() {
        return extraDetails;
    }

    /**
     * Sets the value of the extraDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDetailsType }
     *     
     */
    public void setExtraDetails(ExtraDetailsType value) {
        this.extraDetails = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceType }
     *     
     */
    public DeviceType getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceType }
     *     
     */
    public void setDevice(DeviceType value) {
        this.device = value;
    }

    /**
     * Gets the value of the miscData property.
     * 
     * @return
     *     possible object is
     *     {@link MiscDataType }
     *     
     */
    public MiscDataType getMiscData() {
        return miscData;
    }

    /**
     * Sets the value of the miscData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscDataType }
     *     
     */
    public void setMiscData(MiscDataType value) {
        this.miscData = value;
    }

    /**
     * Gets the value of the errorTxData property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorTxDataType }
     *     
     */
    public ErrorTxDataType getErrorTxData() {
        return errorTxData;
    }

    /**
     * Sets the value of the errorTxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorTxDataType }
     *     
     */
    public void setErrorTxData(ErrorTxDataType value) {
        this.errorTxData = value;
    }

    /**
     * Gets the value of the barcodeTxData property.
     * 
     * @return
     *     possible object is
     *     {@link BarcodeTxDataType }
     *     
     */
    public BarcodeTxDataType getBarcodeTxData() {
        return barcodeTxData;
    }

    /**
     * Sets the value of the barcodeTxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BarcodeTxDataType }
     *     
     */
    public void setBarcodeTxData(BarcodeTxDataType value) {
        this.barcodeTxData = value;
    }

    /**
     * Gets the value of the moneyTxData property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyTxDataType }
     *     
     */
    public MoneyTxDataType getMoneyTxData() {
        return moneyTxData;
    }

    /**
     * Sets the value of the moneyTxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyTxDataType }
     *     
     */
    public void setMoneyTxData(MoneyTxDataType value) {
        this.moneyTxData = value;
    }

    /**
     * Gets the value of the cashFundTransferTxData property.
     * 
     * @return
     *     possible object is
     *     {@link CashFundTransferTxDataType }
     *     
     */
    public CashFundTransferTxDataType getCashFundTransferTxData() {
        return cashFundTransferTxData;
    }

    /**
     * Sets the value of the cashFundTransferTxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashFundTransferTxDataType }
     *     
     */
    public void setCashFundTransferTxData(CashFundTransferTxDataType value) {
        this.cashFundTransferTxData = value;
    }

    /**
     * Gets the value of the imageTxData property.
     * 
     * @return
     *     possible object is
     *     {@link ImageTxDataType }
     *     
     */
    public ImageTxDataType getImageTxData() {
        return imageTxData;
    }

    /**
     * Sets the value of the imageTxData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageTxDataType }
     *     
     */
    public void setImageTxData(ImageTxDataType value) {
        this.imageTxData = value;
    }

    /**
     * Gets the value of the bagNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBagNumber() {
        return bagNumber;
    }

    /**
     * Sets the value of the bagNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBagNumber(String value) {
        this.bagNumber = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the retrievalDate property.
     * 
     * @return
     *     possible object is
     *     {@link RetrievalDateType }
     *     
     */
    public RetrievalDateType getRetrievalDate() {
        return retrievalDate;
    }

    /**
     * Sets the value of the retrievalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrievalDateType }
     *     
     */
    public void setRetrievalDate(RetrievalDateType value) {
        this.retrievalDate = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the extendedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedType() {
        return extendedType;
    }

    /**
     * Sets the value of the extendedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedType(String value) {
        this.extendedType = value;
    }

    /**
     * Gets the value of the vaultFund property.
     * 
     * @return
     *     possible object is
     *     {@link VaultFundType }
     *     
     */
    public VaultFundType getVaultFund() {
        return vaultFund;
    }

    /**
     * Sets the value of the vaultFund property.
     * 
     * @param value
     *     allowed object is
     *     {@link VaultFundType }
     *     
     */
    public void setVaultFund(VaultFundType value) {
        this.vaultFund = value;
    }

    /**
     * Gets the value of the dbChange property.
     * 
     * @return
     *     possible object is
     *     {@link DbChangeType }
     *     
     */
    public DbChangeType getDbChange() {
        return dbChange;
    }

    /**
     * Sets the value of the dbChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbChangeType }
     *     
     */
    public void setDbChange(DbChangeType value) {
        this.dbChange = value;
    }

    /**
     * Gets the value of the isPreExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPreExchange() {
        return isPreExchange;
    }

    /**
     * Sets the value of the isPreExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPreExchange(String value) {
        this.isPreExchange = value;
    }

    /**
     * Gets the value of the deviceErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceErrorCode() {
        return deviceErrorCode;
    }

    /**
     * Sets the value of the deviceErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceErrorCode(String value) {
        this.deviceErrorCode = value;
    }

    /**
     * Gets the value of the doorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoorName() {
        return doorName;
    }

    /**
     * Sets the value of the doorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoorName(String value) {
        this.doorName = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the bagCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBagCount() {
        return bagCount;
    }

    /**
     * Sets the value of the bagCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBagCount(String value) {
        this.bagCount = value;
    }

    /**
     * Gets the value of the cashBagCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashBagCount() {
        return cashBagCount;
    }

    /**
     * Sets the value of the cashBagCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashBagCount(String value) {
        this.cashBagCount = value;
    }

    /**
     * Gets the value of the checkBagCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckBagCount() {
        return checkBagCount;
    }

    /**
     * Sets the value of the checkBagCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckBagCount(String value) {
        this.checkBagCount = value;
    }

    /**
     * Gets the value of the mediaDetected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaDetected() {
        return mediaDetected;
    }

    /**
     * Sets the value of the mediaDetected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaDetected(String value) {
        this.mediaDetected = value;
    }

    /**
     * Gets the value of the netValue property.
     * 
     * @return
     *     possible object is
     *     {@link NetValueType }
     *     
     */
    public NetValueType getNetValue() {
        return netValue;
    }

    /**
     * Sets the value of the netValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetValueType }
     *     
     */
    public void setNetValue(NetValueType value) {
        this.netValue = value;
    }

    /**
     * Gets the value of the customData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomDataType }
     *     
     */
    public CustomDataType getCustomData() {
        return customData;
    }

    /**
     * Sets the value of the customData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomDataType }
     *     
     */
    public void setCustomData(CustomDataType value) {
        this.customData = value;
    }

}
